<?php

/**
 * @file
 * Install, update and uninstall functions for indepth module.
 */

/**
 * Implements hook_install().
 */
function uber_publisher_indepth_install() {
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->getEditable('workflows.workflow.varbase_basic_workflow');
  $config_array = $config->get();
  $config_array['type_settings']['entity_types']['node'][] = 'in_depth';
  $config->set('type_settings', $config_array['type_settings']);
  $config->save();
}
